language: node_js
node_js:
- '8'
cache:
  directories:
  - app/node_modules
  - mobile/node_modules
services:
- docker
env:
- DOCKER_COMPOSE_VERSION=1.22.0
before_install:
- openssl aes-256-cbc -K $encrypted_5e7785341ceb_key -iv $encrypted_5e7785341ceb_iv -in dev/deployment.yml.enc -out dev/deployment.yml -d
- openssl aes-256-cbc -K $encrypted_5e7785341ceb_key -iv $encrypted_5e7785341ceb_iv -in config.enc -out config -d
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
- docker --version
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker-compose --version
- sudo service postgresql stop
- npm install -g npm
- cd app && npm install && cd ..
- npm run test:app:compose
script:
- npm run test:app:build
- npm run test:app:docker
after_script:
  - bash ./telegram_notification.sh
deploy:
- provider: script
  script: bash dev/docker_push ${TRAVIS_COMMIT:0:6}
  on:
    branch: master
- provider: script
  script: bash dev/deploy ${TRAVIS_COMMIT:0:6}
  on:
    branch: master
- provider: script
  script: bash docker_push $TRAVIS_TAG
  on:
    tags: true
