#!/bin/bash
openssl aes-256-cbc -K $encrypted_5e7785341ceb_key -iv $encrypted_5e7785341ceb_iv -in dev/secrets.tar.enc -out dev/secrets.tar -d
tar xvf dev/secrets.tar --directory dev
echo $(pwd)
ls -al dev
echo "Replace IMAGE_TAG in deployment to ${1}"
cat ./dev/deployment.yml | sed 's;IMAGE_TAG;'"${1}"';g' > /tmp/d.yml
echo "Install kubectl"
curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
chmod +x ./kubectl
sudo mv ./kubectl /usr/local/bin/kubectl
echo "Move kubectl config"
mkdir ${HOME}/.kube
mv ./dev/config ${HOME}/.kube/config
echo "Deploy to kubernetes"
kubectl apply -f /tmp/d.yml
